name: Dedupe Dependabot PRs

on:
  push:
    branches: ['dependabot/npm_and_yarn/**']

permissions:
  contents: write

jobs:
  dedupe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Dedupe if needed
        env:
          HUSKY: 0
        run: |
          corepack enable
          yarn dedupe

          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m '[dependabot skip] Dedupe dependencies'
            git push
          fi
